package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("answer", "Id", Answer.class);
		arp.addMapping("donate", "id", Donate.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("question", "Id", Question.class);
		arp.addMapping("sysconf", "id", Sysconf.class);
		arp.addMapping("tag", "Id", Tag.class);
		arp.addMapping("updatelog", "id", Updatelog.class);
		arp.addMapping("user", "id", User.class);
	}
}

