package model;

import model.base.BaseAnswer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Answer extends BaseAnswer<Answer> {
	public static final Answer dao = new Answer().dao();
}
