package model;

import model.base.BaseDonate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Donate extends BaseDonate<Donate> {
	public static final Donate dao = new Donate().dao();
}
