package model;

import model.base.BaseSysconf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysconf extends BaseSysconf<Sysconf> {
	public static final Sysconf dao = new Sysconf().dao();
}
