package model;

import model.base.BaseUpdatelog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Updatelog extends BaseUpdatelog<Updatelog> {
	public static final Updatelog dao = new Updatelog().dao();
}
