package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAnswer<M extends BaseAnswer<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("Id");
	}

	public M setContent(java.lang.String Content) {
		set("Content", Content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("Content");
	}

	public M setSupportCnt(java.lang.Integer SupportCnt) {
		set("SupportCnt", SupportCnt);
		return (M)this;
	}
	
	public java.lang.Integer getSupportCnt() {
		return getInt("SupportCnt");
	}

	public M setOpposeCnt(java.lang.Integer OpposeCnt) {
		set("OpposeCnt", OpposeCnt);
		return (M)this;
	}
	
	public java.lang.Integer getOpposeCnt() {
		return getInt("OpposeCnt");
	}

	public M setAnswerTo(java.lang.String AnswerTo) {
		set("AnswerTo", AnswerTo);
		return (M)this;
	}
	
	public java.lang.String getAnswerTo() {
		return getStr("AnswerTo");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setUserId(java.lang.String UserId) {
		set("UserId", UserId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("UserId");
	}

	public M setAccept(java.lang.Integer accept) {
		set("accept", accept);
		return (M)this;
	}
	
	public java.lang.Integer getAccept() {
		return getInt("accept");
	}

	public M setPraise(java.lang.Integer praise) {
		set("praise", praise);
		return (M)this;
	}
	
	public java.lang.Integer getPraise() {
		return getInt("praise");
	}

}
