package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public M setRmb(java.lang.Integer rmb) {
		set("rmb", rmb);
		return (M)this;
	}
	
	public java.lang.Integer getRmb() {
		return getInt("rmb");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setLogintime(java.util.Date logintime) {
		set("logintime", logintime);
		return (M)this;
	}
	
	public java.util.Date getLogintime() {
		return get("logintime");
	}

	public M setWxopenid(java.lang.String wxopenid) {
		set("wxopenid", wxopenid);
		return (M)this;
	}
	
	public java.lang.String getWxopenid() {
		return getStr("wxopenid");
	}

	public M setQqopenid(java.lang.String qqopenid) {
		set("qqopenid", qqopenid);
		return (M)this;
	}
	
	public java.lang.String getQqopenid() {
		return getStr("qqopenid");
	}

	public M setQuestioncnt(java.lang.Integer questioncnt) {
		set("questioncnt", questioncnt);
		return (M)this;
	}
	
	public java.lang.Integer getQuestioncnt() {
		return getInt("questioncnt");
	}

	public M setAnswercnt(java.lang.Integer answercnt) {
		set("answercnt", answercnt);
		return (M)this;
	}
	
	public java.lang.Integer getAnswercnt() {
		return getInt("answercnt");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setAuth(java.lang.Integer auth) {
		set("auth", auth);
		return (M)this;
	}
	
	public java.lang.Integer getAuth() {
		return getInt("auth");
	}

	public M setExperience(java.lang.Integer experience) {
		set("experience", experience);
		return (M)this;
	}
	
	public java.lang.Integer getExperience() {
		return getInt("experience");
	}

}
