package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setHref(java.lang.String href) {
		set("href", href);
		return (M)this;
	}
	
	public java.lang.String getHref() {
		return getStr("href");
	}

	public M setFrom(java.lang.String from) {
		set("from", from);
		return (M)this;
	}
	
	public java.lang.String getFrom() {
		return getStr("from");
	}

	public M setTo(java.lang.String to) {
		set("to", to);
		return (M)this;
	}
	
	public java.lang.String getTo() {
		return getStr("to");
	}

	public M setFromstatus(java.lang.Integer fromstatus) {
		set("fromstatus", fromstatus);
		return (M)this;
	}
	
	public java.lang.Integer getFromstatus() {
		return getInt("fromstatus");
	}

	public M setTostatus(java.lang.Integer tostatus) {
		set("tostatus", tostatus);
		return (M)this;
	}
	
	public java.lang.Integer getTostatus() {
		return getInt("tostatus");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setFromname(java.lang.String fromname) {
		set("fromname", fromname);
		return (M)this;
	}
	
	public java.lang.String getFromname() {
		return getStr("fromname");
	}

	public M setToname(java.lang.String toname) {
		set("toname", toname);
		return (M)this;
	}
	
	public java.lang.String getToname() {
		return getStr("toname");
	}

	public M setRead(java.lang.Integer read) {
		set("read", read);
		return (M)this;
	}
	
	public java.lang.Integer getRead() {
		return getInt("read");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

}
