package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setId(java.lang.String Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("Id");
	}

	public M setContent(java.lang.String Content) {
		set("Content", Content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("Content");
	}

	public M setSupportCnt(java.lang.Integer SupportCnt) {
		set("SupportCnt", SupportCnt);
		return (M)this;
	}
	
	public java.lang.Integer getSupportCnt() {
		return getInt("SupportCnt");
	}

	public M setOpposeCnt(java.lang.Integer OpposeCnt) {
		set("OpposeCnt", OpposeCnt);
		return (M)this;
	}
	
	public java.lang.Integer getOpposeCnt() {
		return getInt("OpposeCnt");
	}

	public M setCommentTo(java.lang.String CommentTo) {
		set("CommentTo", CommentTo);
		return (M)this;
	}
	
	public java.lang.String getCommentTo() {
		return getStr("CommentTo");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setUserId(java.lang.String UserId) {
		set("UserId", UserId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("UserId");
	}

	public M setHits(java.lang.Integer hits) {
		set("hits", hits);
		return (M)this;
	}
	
	public java.lang.Integer getHits() {
		return getInt("hits");
	}

	public M setStick(java.lang.Integer stick) {
		set("stick", stick);
		return (M)this;
	}
	
	public java.lang.Integer getStick() {
		return getInt("stick");
	}

	public M setComment(java.lang.Integer comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.Integer getComment() {
		return getInt("comment");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setExperience(java.lang.Integer experience) {
		set("experience", experience);
		return (M)this;
	}
	
	public java.lang.Integer getExperience() {
		return getInt("experience");
	}

	public M setAccept(java.lang.String accept) {
		set("accept", accept);
		return (M)this;
	}
	
	public java.lang.String getAccept() {
		return getStr("accept");
	}

}
