package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTag<M extends BaseTag<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("Id");
	}

	public M setTagTo(java.lang.String TagTo) {
		set("TagTo", TagTo);
		return (M)this;
	}
	
	public java.lang.String getTagTo() {
		return getStr("TagTo");
	}

	public M setName(java.lang.String Name) {
		set("Name", Name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

}
